export const LOGIN_ERROR = 'login loading has errored';
export const LOGIN_LOADING = 'login is loading';
export const LOGIN_SUCCESS = 'succesful login';
export const ERROR = 'data loading has errored';
export const LOADING = 'data is loading';
export const SUCCESS = 'succesful fetch of data';
export const START_RANGE = 'start range constant'
export const END_RANGE = 'end range constant';
export const START_ZOOM = 'start zoom constant';
export const END_ZOOM = 'end zoom constant';